# Generated by Django 5.2.3 on 2025-06-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='status',
            field=models.CharField(choices=[('queued', 'QUEUED'), ('sent', 'SENT'), ('failed', 'FAILED')], default='queued', max_length=100),
        ),
    ]
