# Generated by Django 5.2.3 on 2025-07-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_smsmessage_sent_at_contact_smsmessage_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSHistoryRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('delivered', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.contact')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_logs', to='sms.smshistory')),
            ],
        ),
    ]
