# Generated by Django 5.2.3 on 2025-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_smshistoryrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(unique=True),
        ),
    ]
